Edits from R-Ladies review
Bioconductor/biocblog pull request #66
Opened 2024-07-22 15:17 UTC by mblue9

Incorporating feedback from the R-Ladies review to align our post with their suggestions.

2024-08-13 18:53 UTC, jananiravi requested changes
@mblue9 added a few more suggestions based on the discussion here:
https://github.com/rladies/rladies.github.io/pull/340

2024-08-13 18:53 UTC, jananiravi commented on posts/2024-07-20-rladies-bioconductor-collaboration/index.qmd
> +R-Ladies Global started in 2016 and has expanded to more than 200 chapters in 60+ countries worldwide.
```suggestion
R-Ladies Global started in 2016 and has expanded to more than 200 chapters in 60+ countries worldwide.
R-Ladies chapters work alongside other like-minded communities such as [LatinR](https://latin-r.com/en/), [RainbowR](https://rainbowr.netlify.app/), [miR](https://mircommunity.com/), [ArabR](https://arabr.github.io), [AfricaR](https://r4africa.org/), and [AsiaR](https://github.com/asiar-community).
```

2024-08-13 18:53 UTC, jananiravi commented on posts/2024-07-20-rladies-bioconductor-collaboration/index.qmd
>  -   Learn more about our joint efforts at the [Bioconductor Working Group page](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html#r-ladies-and-bioc).
```suggestion
-   Learn more about and partake in our joint initiative at the [Bioconductor Working Group page](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html#r-ladies-and-bioc).
```

2024-08-13 18:53 UTC, jananiravi commented on posts/2024-07-20-rladies-bioconductor-collaboration/index.qmd
`L33–35`: 
-   Jointly host events with local chapters
-   Promote R-Ladies local watch parties of live-casted or pre-recorded events and professional networking events for Bioconductor conferences (using content from BioC: BioC North America, BioCAsia, EuroBioC).
-   Highlight Bioconductor speakers at R + computational biology R-Ladies events across chapters

`L45`:
We `recently kicked` off ... [change tense since it's now in the past]

2025-02-04 11:52 UTC, mblue9 commented
@jananiravi I will close this one, let's use your newer one for the edits.

2025-02-04 11:52 UTC, closed without merging